module.exports = {
	Container: require('./SVGContainer'),
	Controller: require('./SVGController'),
	Creep: require('./SVGCreep'),
	Extension: require('./SVGExtension'),
	Lab: require('./SVGLab'),
	Link: require('./SVGLink'),
	Mineral: require('./SVGMineral'),
	Nuker: require('./SVGNuker'),
	Room: require('./SVGRoom'),
	Source: require('./SVGSource'),
	Spawn: require('./SVGSpawn'),
	Storage: require('./SVGStorage'),
	Terminal: require('./SVGTerminal'),
	Tower: require('./SVGTower'),
};
