module.exports = {
	Container: require('./SVGContainer'),
	Controller: require('./SVGController'),
	Creep: require('./SVGCreep'),
	Extension: require('./SVGExtension'),
	Extractor: require('./SVGExtractor'),
	KeeperLair: require('./SVGKeeperLair'),
	Lab: require('./SVGLab'),
	Link: require('./SVGLink'),
	Mineral: require('./SVGMineral'),
	Nuker: require('./SVGNuker'),
	Observer: require('./SVGObserver'),
	PowerBank: require('./SVGPowerBank'),
	PowerSpawn: require('./SVGPowerSpawn'),
	Resource: require('./SVGResource'),
	Room: require('./SVGRoom'),
	Source: require('./SVGSource'),
	Spawn: require('./SVGSpawn'),
	Storage: require('./SVGStorage'),
	Terminal: require('./SVGTerminal'),
	Tower: require('./SVGTower'),
};
